---
title: "Plot_ly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

```{r}
library(p8105.datasets)
data("ny_noaa") 
```

```{r}
ny_noaa =
  ny_noaa %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.integer(year),
         month = factor(month.name[as.integer(month)], levels = month.name),
         day = as.integer(day),
         prcp = prcp / 10,
         tmax = as.numeric(tmax) / 10,
         tmin = as.numeric(tmin) / 10) %>% 
  sample_n(50000)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Minimum and Maximum temperature mapping precipitation in 2009

```{r}
xlab = list(title = "Minimum temperature(°C)")
ylab = list(title = "Maximum temperature(°C)")

ny_noaa %>% 
  filter(year == 2009,
         !is.na(tmax),
         !is.na(tmin),
         !is.na(prcp),
         prcp > 0) %>%
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~ prcp) %>% 
  layout(xaxis = xlab, yaxis = ylab)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Maximum temperature by month in 2009

```{r}
xlab = list(title = "Month")
ylab = list(title = "Maximum temperature(°C)")

ny_noaa %>% 
  filter(year == 2009,
         !is.na(tmax),
         !is.na(tmin),
         !is.na(prcp)) %>% 
  plot_ly(x = ~month, y = ~tmax, color = ~month, type = "box") %>% 
  layout(xaxis = xlab, yaxis = ylab)
```

### Precipitation by month in 2009

```{r}
xlab = list(title = "Month")
ylab = list(title = "Precipitation(mm)")

ny_noaa %>% 
  filter(year == 2009,
         !is.na(tmax),
         !is.na(tmin),
         !is.na(prcp)) %>% 
  plot_ly(x = ~month, y = ~prcp, color = ~month, type = "bar") %>% 
  layout(xaxis = xlab, yaxis = ylab)
```


